### ISSUE TITLE
err on empty lines

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_extended_selection#2]
clicked n times (with shift, w/o it) on empty document.
```
Init: cuda_extended_selection
Extended double-click selection: Missing config file. Creating a default one.
Init: cuda_hilite_occurrences
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_extended_selection/ext_sel.py", line 60, in on_click_dbl
    self.calc_selections()
  File "/home/user/.config/cudatext/py/cuda_extended_selection/ext_sel.py", line 73, in calc_selections
    comment_str = lexer_proc(LEXER_GET_PROP, lex)["c_line"]  
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_extended_selection/ext_sel.py", line 60, in on_click_dbl
    self.calc_selections()
  File "/home/user/.config/cudatext/py/cuda_extended_selection/ext_sel.py", line 73, in calc_selections
    comment_str = lexer_proc(LEXER_GET_PROP, lex)["c_line"]  
TypeError: 'NoneType' object is not subscriptable
Init: cuda_addonman
```

**Comment by halfbrained** [comment]
I fixed this already a month ago, right? I'm pretty sure this is the case of "~~old~~ man gets confused with github" :)
Fixed it again.
